### ISSUE TITLE
Can't find modules Qt5WidgetsConfig.cmake, qt5widgets-config.cmake

### ISSUE THREAD

**Issue by demiurg337** [euler0/mini-cmake-qt#3]
Hi, thanks for your tutorial, but when I tried do build your project I had

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake
(on Ubuntu 18.04)
Installing of $sudo apt-get install qtbase5-dev has fixed it.
References
https://github.com/MTG/acousticbrainz-gui/issues/20
https://askubuntu.com/questions/508503/whats-the-development-package-for-qt5-in-14-04

Can you add this some of this links to READEME? (or can I add add it by pull request?)

**Comment by euler0** [comment]
I had assumed that Qt is installed properly. I’ll update the README soon.

Thanks for your feedback, @demiurg337! 🙏
